spring:
  sql:
    init:
      mode: always
  main:
    banner-mode: off
  application:
    name: spring-database-jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

server:
  port: 8090


